### ISSUE TITLE
deallogの表示時刻が何かおかしい

### ISSUE THREAD

**Issue by sifue** [sifue/n-coin-bot#18]
DB上にはJSTで入っているので調整が必要かもしれません。
![2018-03-12 16 56 43](https://user-images.githubusercontent.com/60450/37271477-67687116-2616-11e8-902f-44718aca4400.png)

**Comment by sifue** [comment]
@uehr になおしてもらいたい所。

**Comment by uehr** [comment]
対応します

**Comment by sifue** [comment]
https://github.com/sifue/n-coin-bot/pull/16
で修正を確認。
