### ISSUE TITLE
Sequalizeのdecrementメソッドを使ってほしい

### ISSUE THREAD

**Issue by sifue** [sifue/n-coin-bot#36]
とりあえずマージするけど、Sequalizeのdecrementメソッドを使わないとトランザクショナルじゃないので、修正してほしいかも。
http://docs.sequelizejs.com/class/lib/model.js~Model.html#static-method-decrement

https://github.com/sifue/n-coin-bot/pull/35

**Comment by uehr** [comment]
https://github.com/sifue/n-coin-bot/pull/38

**Comment by uehr** [comment]
出品時刻からオークション終了日時を計算する仕様へ移行し、timeLimitをアップデートする必要は無くなりました。

**Comment by uehr** [comment]
対応済み
